### ISSUE TITLE
activity 切换实现

### ISSUE THREAD

**Issue by gujingjing** [A-W-C-J/LiteRead#1]
我看见在android 
ArticleListActivity界面，里点击跳转的界面是从下到上进入的，
正常界面是从左像右移动的，
但是，代码里面没有找到你的实现方法，请赐教一下哈！谢谢啦！

**Comment by A-W-C-J** [comment]
这是[FinestWebView](https://github.com/TheFinestArtist/FinestWebView-Android)这个三方库实现的  具体实现代码：  
 protected void show(String url, String data) {
            this.url = url;
            this.data = data;
            this.key = System.identityHashCode(this);

            if (!listeners.isEmpty()) new BroadCastManager(context, key, listeners);

            Intent intent = new Intent(context, FinestWebViewActivity.class);
            intent.putExtra("builder", this);

            Ctx.startActivity(intent);

            if (context instanceof Activity)
                ((Activity) context).overridePendingTransition(animationOpenEnter, animationOpenExit);
        }
主要就是   ((Activity) context).overridePendingTransition(animationOpenEnter, animationOpenExit);这一句了，animationOpenEnter是进入动画，animationOpenExit是退出动画

**Comment by A-W-C-J** [comment]
这是[FinestWebView](https://github.com/TheFinestArtist/FinestWebView-Android)这个三方库实现的 具体实现代码：

protected void show(String url, String data) {
this.url = url;
this.data = data;
this.key = System.identityHashCode(this);

        if (!listeners.isEmpty()) new BroadCastManager(context, key, listeners);

        Intent intent = new Intent(context, FinestWebViewActivity.class);
        intent.putExtra("builder", this);

        Ctx.startActivity(intent);

        if (context instanceof Activity)
            ((Activity) context).overridePendingTransition(animationOpenEnter, animationOpenExit);
    }
主要就是 ((Activity) context).overridePendingTransition(animationOpenEnter, animationOpenExit);这一句了，animationOpenEnter是进入动画，animationOpenExit是退出动画

**Comment by gujingjing** [comment]
那正常界面之间的切换动画是怎么做的呢，代码里好像没找到呢，比如知乎日报界面（左边菜单栏点击之后的界面）

**Comment by A-W-C-J** [comment]
你指的是activity间的转场动画吗？res目录下面的anim文件夹里定义了从左到右的动画。跳转的时候，在startActivity之后加上
overridePendingTransition(进入动画, 退出动画)；但其实默认的动画就是从左到右，可以不用写的。基本的activity转场动画都是这样实现的。这里只是一个示范。更多的转场动画可以参考[https://github.com/lgvalle/Material-Animations](https://github.com/lgvalle/Material-Animations)；本项目基本还没有实现什么动画的，我也是在学习动画中...

**Comment by A-W-C-J** [comment]
如果你有什么很好的动画项目 欢迎推荐给我学习一下
